Parth/ss 14 user can create an account and login
Capstone-Projects-2023-Fall/project-smartspeech pull request #41
Opened 2023-10-15 12:31 UTC by cvto1021

- Finally, The login is running properly on the server
- Implemented the backbone for the login authentication using Github and Google
- Created the Login page for the Sign In and Sign Out
- Attempted to add more Login Auths
- Parth helped with some of the debugging ~ thank you!
- Added the Firebase DB to the Google sign-in
- Debugged some new errors when running on the server
- Added a name feature for when the users are able to sign-in

2023-10-15 16:35 UTC, Parth099 requested changes

2023-10-15 16:35 UTC, Parth099 commented on frontend/.env
no secrets in .env use .env.local and **gitignore** it

2023-10-15 16:35 UTC, Parth099 commented on frontend/src/components/login.tsx
```
 className="btn btn-primary
 ```
 
 is this styling defined anywhere, it does not render the style. Looks to be bootstrap; we are not using bootstrap

2023-10-15 16:35 UTC, Parth099 commented on frontend/src/react-state-management/providers/providersWrapper.tsx
is this wrapper required? Recall to use `SessionProvider` you need to pass a session var in. It is probably not a good idea to use a wrapper here unless you inject  a `session` argument.

See: https://next-auth.js.org/getting-started/client#custom-client-session-handling

2023-10-15 16:58 UTC, cvto1021 commented on frontend/.env
fixed it!

2023-10-15 17:01 UTC, cvto1021 commented on frontend/src/components/login.tsx
okay, fixed that too!

2023-10-15 21:41 UTC, cvto1021 commented on frontend/src/react-state-management/providers/providersWrapper.tsx
This ProviderWrapper is used in the _app.js to run properly. I added a provider in the login page that detects if the SignIn is authenticated, then users would have access to the tiles page. Lastly, I also deleted the SignOut page since it was called in the login page.

2023-10-15 21:41 UTC, cvto1021 commented on frontend/src/react-state-management/providers/providersWrapper.tsx
Fixed it!

2023-10-16 12:09 UTC, Parth099 approved these changes

2023-10-25 18:49 UTC, closed without merging